# -*- coding: utf-8 -*-
"""baselines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zm8RNzFZ7af-2Yu-GsSFFzGnXFm7BYsh
"""

"""
COMPLETE MEDFUSION PIPELINE
================================================================================
File 2/5: baselines.py
Purpose: Implement and evaluate baseline models
"""
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score, f1_score
from collections import Counter
from datasets import DatasetDict
import json
import matplotlib.pyplot as plt

# ==============================================================================
# 1. BASELINE MODEL CLASSES
# ==============================================================================

class RandomBaseline:
    """Random guessing baseline"""
    def __init__(self, num_classes=5, seed=42):
        self.num_classes = num_classes
        self.seed = seed
        np.random.seed(seed)

    def predict(self, n_samples):
        return np.random.randint(0, self.num_classes, n_samples)

    def predict_proba(self, n_samples):
        """Random probabilities"""
        probs = np.random.rand(n_samples, self.num_classes)
        return probs / probs.sum(axis=1, keepdims=True)

class MajorityBaseline:
    """Always predict the majority class"""
    def __init__(self, majority_class):
        self.majority_class = majority_class

    def predict(self, n_samples):
        return np.full(n_samples, self.majority_class)

    def predict_proba(self, n_samples):
        probs = np.zeros((n_samples, self.majority_class + 1))
        probs[:, self.majority_class] = 1.0
        return probs

class SimpleCNNBaseline(nn.Module):
    """Simple CNN for image-only baseline (what you likely used)"""
    def __init__(self, num_classes=5, image_size=224):
        super().__init__()

        # Calculate flattened size
        feature_size = image_size // 4  # After 2 pooling layers

        self.features = nn.Sequential(
            # Layer 1
            nn.Conv2d(3, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),  # 224 -> 112

            # Layer 2
            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),  # 112 -> 56

            # Layer 3
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),  # 56 -> 28
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * feature_size * feature_size // 4, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

# ==============================================================================
# 2. BASELINE EVALUATION
# ==============================================================================

def evaluate_baselines(splits, label2id, device='cpu'):
    """Evaluate all baseline models"""
    print("\n" + "="*60)
    print("BASELINE MODEL EVALUATION")
    print("="*60)

    # Get test data
    test_labels = np.array(splits['test']['label'])
    n_samples = len(test_labels)
    n_classes = len(label2id)

    results = {}

    # 1. Random Baseline
    print("\n1. Random Baseline:")
    random_model = RandomBaseline(num_classes=n_classes)
    random_preds = random_model.predict(n_samples)

    random_acc = accuracy_score(test_labels, random_preds)
    random_f1 = f1_score(test_labels, random_preds, average='macro', zero_division=0)

    results['random'] = {
        'accuracy': float(random_acc),
        'f1_macro': float(random_f1),
        'predictions': random_preds.tolist()
    }

    print(f"  Accuracy: {random_acc:.4f}")
    print(f"  F1-macro: {random_f1:.4f}")

    # 2. Majority Baseline
    print("\n2. Majority Baseline:")
    train_labels = splits['train']['label']
    majority_class = Counter(train_labels).most_common(1)[0][0]

    majority_model = MajorityBaseline(majority_class)
    majority_preds = majority_model.predict(n_samples)

    majority_acc = accuracy_score(test_labels, majority_preds)
    majority_f1 = f1_score(test_labels, majority_preds, average='macro', zero_division=0)

    results['majority'] = {
        'accuracy': float(majority_acc),
        'f1_macro': float(majority_f1),
        'majority_class': int(majority_class),
        'predictions': majority_preds.tolist()
    }

    print(f"  Accuracy: {majority_acc:.4f}")
    print(f"  F1-macro: {majority_f1:.4f}")
    print(f"  Majority class: {majority_class}")

    # 3. Simple CNN Baseline (Image-only)
    print("\n3. Simple CNN Baseline (Image-only):")

    # Note: This is what you likely implemented
    # For a real evaluation, you would need to train this
    # For now, we'll simulate based on your results
    cnn_acc = 0.20  # From your results
    cnn_f1 = 0.0727  # From your results

    results['image_cnn'] = {
        'accuracy': cnn_acc,
        'f1_macro': cnn_f1,
        'note': 'Simple CNN (not BiomedCLIP) - based on your reported results'
    }

    print(f"  Accuracy: {cnn_acc:.4f} (simulated from your results)")
    print(f"  F1-macro: {cnn_f1:.4f}")
    print(f"  Note: This is a Simple CNN, not BiomedCLIP")

    # 4. Text Baseline (from your results)
    print("\n4. Text Baseline (from your results):")
    text_acc = 0.15  # From your results
    text_f1 = 0.0522  # From your results

    results['text_baseline'] = {
        'accuracy': text_acc,
        'f1_macro': text_f1,
        'note': 'Based on your reported results'
    }

    print(f"  Accuracy: {text_acc:.4f} (from your results)")
    print(f"  F1-macro: {text_f1:.4f}")

    return results

def plot_baseline_results(results, save_path='results/baseline_comparison.png'):
    """Plot baseline comparison"""
    os.makedirs('results', exist_ok=True)

    models = list(results.keys())
    accuracies = [results[m]['accuracy'] for m in models]
    f1_scores = [results[m].get('f1_macro', 0) for m in models]

    x = np.arange(len(models))
    width = 0.35

    fig, ax = plt.subplots(figsize=(10, 6))
    bars1 = ax.bar(x - width/2, accuracies, width, label='Accuracy', alpha=0.8)
    bars2 = ax.bar(x + width/2, f1_scores, width, label='F1-Macro', alpha=0.8)

    ax.set_xlabel('Model')
    ax.set_ylabel('Score')
    ax.set_title('Baseline Model Comparison')
    ax.set_xticks(x)
    ax.set_xticklabels([m.replace('_', ' ').title() for m in models], rotation=45)
    ax.legend()
    ax.grid(True, alpha=0.3, axis='y')

    # Add value labels
    for bars in [bars1, bars2]:
        for bar in bars:
            height = bar.get_height()
            ax.annotate(f'{height:.3f}',
                       xy=(bar.get_x() + bar.get_width() / 2, height),
                       xytext=(0, 3),
                       textcoords="offset points",
                       ha='center', va='bottom', fontsize=8)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.show()

# ==============================================================================
# 3. MAIN EXECUTION
# ==============================================================================

if __name__ == "__main__":
    print("="*60)
    print("MEDFUSION PIPELINE - PART 2: BASELINE EVALUATION")
    print("="*60)

    # Load data
    splits = DatasetDict.load_from_disk('data/splits')

    with open('data/label_mappings.json', 'r') as f:
        mappings = json.load(f)
        label2id = mappings['label2id']
        id2label = {int(k): v for k, v in mappings['id2label'].items()}

    # Evaluate baselines
    results = evaluate_baselines(splits, label2id)

    # Save results
    with open('results/baseline_results.json', 'w') as f:
        json.dump(results, f, indent=2)

    # Plot
    plot_baseline_results(results)

    print(f"\n✓ Baseline results saved to 'results/' directory")