# -*- coding: utf-8 -*-
"""medfusion_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U46Nc80N-M2AAL_M-U8s9A3cXd9klj02
"""

"""
COMPLETE MEDFUSION PIPELINE
================================================================================
File 3/5: medfusion_model.py
Purpose: Define the MedFusion model architecture
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import AutoModel, AutoTokenizer
import warnings
warnings.filterwarnings('ignore')

# ==============================================================================
# 1. MEDFUSION MODEL ARCHITECTURE
# ==============================================================================

class MedFusion(nn.Module):
    """
    MedFusion: Multimodal VQA model

    Truth: We're using Bio_ClinicalBERT for text and a Simple CNN for images
    NOT using BiomedCLIP (despite earlier claims in architecture diagram)
    """

    def __init__(self, num_classes=5, dropout=0.3, use_simple_cnn=True):
        super().__init__()

        print("Initializing MedFusion...")
        print("  Text encoder: Bio_ClinicalBERT")
        print("  Image encoder: Simple CNN (not BiomedCLIP)")

        # ============================================
        # TEXT ENCODER: Bio_ClinicalBERT
        # ============================================
        try:
            self.text_encoder = AutoModel.from_pretrained(
                "emilyalsentzer/Bio_ClinicalBERT"
            )
            self.text_proj = nn.Linear(768, 256)
            print("  ✓ Loaded Bio_ClinicalBERT")
        except:
            print("  ✗ Could not load Bio_ClinicalBERT, using placeholder")
            self.text_encoder = None
            self.text_proj = nn.Linear(768, 256)

        # ============================================
        # IMAGE ENCODER: Simple CNN (TRUTH)
        # ============================================
        if use_simple_cnn:
            # This is what you actually used based on 20% baseline
            self.image_encoder = nn.Sequential(
                # Block 1
                nn.Conv2d(3, 16, kernel_size=3, padding=1),
                nn.BatchNorm2d(16),
                nn.ReLU(),
                nn.MaxPool2d(2),  # 224 -> 112

                # Block 2
                nn.Conv2d(16, 32, kernel_size=3, padding=1),
                nn.BatchNorm2d(32),
                nn.ReLU(),
                nn.MaxPool2d(2),  # 112 -> 56

                # Block 3
                nn.Conv2d(32, 64, kernel_size=3, padding=1),
                nn.BatchNorm2d(64),
                nn.ReLU(),
                nn.MaxPool2d(2),  # 56 -> 28

                # Global pooling
                nn.AdaptiveAvgPool2d((1, 1)),
                nn.Flatten(),
                nn.Linear(64, 256)
            )
            print("  ✓ Using Simple CNN image encoder")
        else:
            # Placeholder for actual BiomedCLIP (not implemented)
            self.image_encoder = None
            print("  ✗ BiomedCLIP not implemented")

        # ============================================
        # FUSION AND CLASSIFICATION
        # ============================================
        self.fusion_dropout = nn.Dropout(dropout)
        self.fusion_layer = nn.Linear(512, 256)  # 256 + 256 = 512
        self.classifier = nn.Linear(256, num_classes)

        # Tokenizer
        try:
            self.tokenizer = AutoTokenizer.from_pretrained(
                "emilyalsentzer/Bio_ClinicalBERT"
            )
        except:
            self.tokenizer = None

        # Freeze text encoder initially
        if self.text_encoder:
            for param in self.text_encoder.parameters():
                param.requires_grad = False

        print(f"  Total parameters: {sum(p.numel() for p in self.parameters()):,}")
        print(f"  Trainable parameters: {sum(p.numel() for p in self.parameters() if p.requires_grad):,}")

    def forward(self, input_ids, attention_mask, pixel_values):
        """
        Forward pass

        Args:
            input_ids: Tokenized text [batch, seq_len]
            attention_mask: Attention mask [batch, seq_len]
            pixel_values: Images [batch, 3, 224, 224]
        """
        batch_size = pixel_values.shape[0]

        # ============================================
        # TEXT ENCODING
        # ============================================
        if self.text_encoder is not None:
            text_outputs = self.text_encoder(
                input_ids=input_ids,
                attention_mask=attention_mask
            )
            # Use [CLS] token
            text_features = text_outputs.last_hidden_state[:, 0, :]
        else:
            # Placeholder if text encoder failed to load
            text_features = torch.randn(batch_size, 768, device=pixel_values.device)

        text_features = F.relu(self.text_proj(text_features))

        # ============================================
        # IMAGE ENCODING
        # ============================================
        if self.image_encoder is not None:
            image_features = self.image_encoder(pixel_values)
        else:
            # Placeholder
            image_features = torch.randn(batch_size, 256, device=pixel_values.device)

        # ============================================
        # LATE FUSION
        # ============================================
        fused_features = torch.cat([text_features, image_features], dim=1)
        fused_features = self.fusion_dropout(fused_features)

        # ============================================
        # CLASSIFICATION
        # ============================================
        fused_features = F.relu(self.fusion_layer(fused_features))
        logits = self.classifier(fused_features)

        return logits

    def get_tokenizer(self):
        """Get tokenizer for text preprocessing"""
        return self.tokenizer

# ==============================================================================
# 2. DATASET CLASS
# ==============================================================================

import requests
from PIL import Image
from io import BytesIO
import torchvision.transforms as transforms

class MedFusionDataset(torch.utils.data.Dataset):
    """Dataset for MedFusion with image downloading"""

    def __init__(self, dataset_split, tokenizer, max_length=128, image_size=224):
        self.dataset = dataset_split
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.image_size = image_size

        # Image transforms
        self.transform = transforms.Compose([
            transforms.Resize((image_size, image_size)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                               std=[0.229, 0.224, 0.225])
        ])

        # Preprocess texts
        self._preprocess_texts()

    def _preprocess_texts(self):
        """Preprocess all text once"""
        self.texts = []

        for example in self.dataset:
            question = example["Question"]

            # Get options
            options = []
            for letter in ["A", "B", "C", "D", "E"]:
                col_name = f"Answer{letter}"
                if col_name in example and example[col_name]:
                    options.append(f"{letter}. {example[col_name]}")

            # Format: "Question: [text] Options: A. ... B. ..."
            if options:
                text = f"Question: {question} Options: " + " | ".join(options[:3])
            else:
                text = f"Question: {question}"

            self.texts.append(text)

    def __len__(self):
        return len(self.dataset)

    def _download_image(self, url):
        """Download image from URL"""
        try:
            response = requests.get(url, timeout=5)
            image = Image.open(BytesIO(response.content)).convert("RGB")
            return image
        except:
            # Return black image if download fails
            return Image.new('RGB', (self.image_size, self.image_size), (0, 0, 0))

    def __getitem__(self, idx):
        example = self.dataset[idx]

        # Text
        text = self.texts[idx]
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt"
        )

        # Image
        image_url = example["Image url"]
        image = self._download_image(image_url)
        image_tensor = self.transform(image)

        # Label
        label = torch.tensor(example["label"], dtype=torch.long)

        return {
            "input_ids": encoding["input_ids"].squeeze(),
            "attention_mask": encoding["attention_mask"].squeeze(),
            "pixel_values": image_tensor,
            "labels": label
        }

# ==============================================================================
# 3. TEST THE MODEL
# ==============================================================================

if __name__ == "__main__":
    print("="*60)
    print("MEDFUSION MODEL ARCHITECTURE TEST")
    print("="*60)

    # Create model
    model = MedFusion(num_classes=5)

    # Test with dummy data
    batch_size = 2
    seq_len = 128

    dummy_input_ids = torch.randint(0, 1000, (batch_size, seq_len))
    dummy_attention_mask = torch.ones((batch_size, seq_len))
    dummy_images = torch.randn((batch_size, 3, 224, 224))

    # Forward pass
    with torch.no_grad():
        logits = model(
            input_ids=dummy_input_ids,
            attention_mask=dummy_attention_mask,
            pixel_values=dummy_images
        )

    print(f"\nModel test successful!")
    print(f"Input shapes:")
    print(f"  Text: {dummy_input_ids.shape}")
    print(f"  Images: {dummy_images.shape}")
    print(f"Output logits shape: {logits.shape}")
    print(f"Number of classes: {logits.shape[1]}")

    # Test tokenizer if available
    if model.tokenizer:
        sample_text = "Question: What does this curve show?"
        tokens = model.tokenizer(sample_text, truncation=True, max_length=128)
        print(f"\nTokenizer test: {len(tokens['input_ids'])} tokens")

    # Save model architecture diagram
    print(f"\n✓ Model architecture ready for training")
    print("Note: Using Simple CNN for images (not BiomedCLIP)")

