# -*- coding: utf-8 -*-
"""setup_and_config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quJ8HdqjIQwLZssSEf-TfE7JERIwKGKr
"""

"""
COMPLETE MEDFUSION PIPELINE
================================================================================
File 1/5: setup_and_config.py
Purpose: Initialize project, set up environment, load dataset
"""
import torch
import numpy as np
import pandas as pd
from datasets import load_dataset, DatasetDict
import os
import json
import random
from sklearn.model_selection import train_test_split

# ==============================================================================
# 1. SETUP AND CONFIGURATION
# ==============================================================================

def set_seed(seed=42):
    """Set all random seeds for reproducibility"""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
    return seed

def setup_environment():
    """Setup directories and device"""
    # Create directories
    dirs = ['data', 'models', 'results', 'checkpoints', 'logs']
    for d in dirs:
        os.makedirs(d, exist_ok=True)

    # Device setup
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    return device

# ==============================================================================
# 2. DATASET LOADING AND EDA
# ==============================================================================

def load_mmmed_dataset():
    """Load and explore MMMED dataset"""
    print("Loading MMMED dataset...")
    dataset = load_dataset("praiselab-picuslab/MMMED")

    # Use English split
    if 'English' in dataset:
        ds = dataset['English']
        print(f"✓ Loaded English split: {len(ds)} samples")
    else:
        ds = dataset[list(dataset.keys())[0]]
        print(f"✓ Loaded {list(dataset.keys())[0]} split: {len(ds)} samples")

    # Convert to pandas for EDA
    df = ds.to_pandas()

    print("\n=== Dataset Summary ===")
    print(f"Total samples: {len(df)}")
    print(f"Columns: {list(df.columns)}")
    print(f"Sample question: {df['Question'].iloc[0][:100]}...")

    # Class distribution
    class_dist = df['Correct Letter'].value_counts()
    print(f"\nClass distribution (Correct Letter):")
    for letter, count in class_dist.items():
        print(f"  {letter}: {count} samples ({count/len(df)*100:.1f}%)")

    return ds, df

# ==============================================================================
# 3. DATA PREPROCESSING
# ==============================================================================

def prepare_labels(dataset, label_column='Correct Letter'):
    """Convert string labels to numeric IDs"""
    print(f"\nPreparing labels from '{label_column}'...")

    # Get unique labels and create mappings
    unique_labels = sorted(list(set(dataset[label_column])))
    label2id = {label: idx for idx, label in enumerate(unique_labels)}
    id2label = {idx: label for label, idx in label2id.items()}

    print(f"Found {len(unique_labels)} classes: {unique_labels}")
    print(f"Label mapping: {label2id}")

    # Apply mapping
    def map_label(example):
        example['label'] = label2id[example[label_column]]
        return example

    labeled_ds = dataset.map(map_label)

    # Verify mapping
    labels = labeled_ds['label']
    unique, counts = np.unique(labels, return_counts=True)
    print("\nLabel distribution after mapping:")
    for label_id, count in zip(unique, counts):
        print(f"  Class {label_id} ({id2label[label_id]}): {count} samples")

    return labeled_ds, label2id, id2label

def create_stratified_splits(dataset, test_size=0.15, val_size=0.15, seed=42):
    """Create train/val/test splits with stratification"""
    print(f"\nCreating splits (test={test_size}, val={val_size})...")

    # Get indices and labels
    indices = list(range(len(dataset)))
    labels = dataset['label']

    # First split: train vs (val+test)
    train_idx, temp_idx = train_test_split(
        indices,
        test_size=(val_size + test_size),
        stratify=labels,
        random_state=seed,
        shuffle=True
    )

    # Second split: val vs test
    temp_labels = [labels[i] for i in temp_idx]
    val_idx, test_idx = train_test_split(
        temp_idx,
        test_size=test_size/(val_size + test_size),
        stratify=temp_labels,
        random_state=seed,
        shuffle=True
    )

    # Create DatasetDict
    splits = DatasetDict({
        'train': dataset.select(train_idx),
        'val': dataset.select(val_idx),
        'test': dataset.select(test_idx)
    })

    # Print statistics
    print("\nSplit Statistics:")
    for split_name in ['train', 'val', 'test']:
        split = splits[split_name]
        split_labels = split['label']
        n_samples = len(split)

        unique, counts = np.unique(split_labels, return_counts=True)
        print(f"\n{split_name.upper()} ({n_samples} samples):")
        for label_id, count in zip(unique, counts):
            print(f"  Class {label_id}: {count} samples ({count/n_samples*100:.1f}%)")

    return splits

# ==============================================================================
# 4. MAIN EXECUTION
# ==============================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("MEDFUSION PIPELINE - PART 1: SETUP AND DATA PREPARATION")
    print("=" * 60)

    # Setup
    device = setup_environment()
    set_seed(42)

    # Load data
    dataset, df = load_mmmed_dataset()

    # Prepare labels
    labeled_dataset, label2id, id2label = prepare_labels(dataset)

    # Create splits (~135/39/20 samples for 194 total)
    splits = create_stratified_splits(
        labeled_dataset,
        test_size=0.10,  # ~20 samples
        val_size=0.20,   # ~39 samples
        seed=42
    )

    # Save everything
    splits.save_to_disk('data/splits')
    with open('data/label_mappings.json', 'w') as f:
        json.dump({'label2id': label2id, 'id2label': id2label}, f, indent=2)

    print(f"\n✓ Data saved to 'data/' directory")
    print(f"✓ Ready for model training")