# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uT83WbRJy7NBV09sjwQhtN19QkmDJjZF
"""

"""
COMPLETE MEDFUSION PIPELINE
================================================================================
File 4/5: training.py (COMPLETE VERSION)
Purpose: Train and evaluate MedFusion
"""
import torch
import torch.nn as nn
import torch.nn.functional as F # Added from medfusion_model
from torch.utils.data import DataLoader
from transformers import AutoModel, AutoTokenizer # Added from medfusion_model
import numpy as np
from tqdm import tqdm
import json
import os
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import warnings # Added from medfusion_model
warnings.filterwarnings('ignore') # Added from medfusion_model

# Imports for MedFusionDataset (moved from medfusion_model)
import requests
from PIL import Image
from io import BytesIO
import torchvision.transforms as transforms

# ==============================================================================
# 1. TRAINER CLASS
# ==============================================================================

class MedFusionTrainer:
    """Trainer for MedFusion with class weighting"""

    def __init__(self, model, device, class_weights=None, learning_rate=2e-5):
        self.model = model
        self.device = device
        self.model.to(device)

        # Weighted loss for class imbalance
        if class_weights is not None:
            class_weights = torch.tensor(class_weights, device=device, dtype=torch.float32)
            self.criterion = nn.CrossEntropyLoss(weight=class_weights)
            print(f"Using weighted loss with weights: {class_weights.cpu().numpy()}")
        else:
            self.criterion = nn.CrossEntropyLoss()

        # Optimizer - only train unfrozen parameters
        trainable_params = [p for p in model.parameters() if p.requires_grad]
        self.optimizer = torch.optim.AdamW(
            trainable_params,
            lr=learning_rate,
            weight_decay=0.01
        )

        # Learning rate scheduler
        self.scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            self.optimizer, T_max=20
        )

        # Track history
        self.history = {
            'train_loss': [], 'train_acc': [],
            'val_loss': [], 'val_acc': [],
            'test_loss': None, 'test_acc': None
        }

    def calculate_class_weights(self, train_labels):
        """Calculate weights inversely proportional to class frequency"""
        from collections import Counter
        counts = Counter(train_labels)
        n_classes = len(counts)
        total = sum(counts.values())

        weights = []
        for class_id in range(n_classes):
            if class_id in counts:
                weight = total / (n_classes * counts[class_id])
            else:
                weight = 1.0  # Default if class missing
            weights.append(weight)

        # Normalize
        weights = torch.tensor(weights, dtype=torch.float32)
        weights = weights / weights.sum() * n_classes

        return weights.tolist()

    def train_epoch(self, train_loader, epoch):
        """Train for one epoch"""
        self.model.train()
        total_loss = 0
        correct = 0
        total = 0

        pbar = tqdm(train_loader, desc=f"Epoch {epoch} Training")
        for batch_idx, batch in enumerate(pbar):
            # Move to device
            batch = {k: v.to(self.device) for k, v in batch.items()}
            labels = batch['labels']

            # Forward pass
            self.optimizer.zero_grad()
            logits = self.model(
                input_ids=batch['input_ids'],
                attention_mask=batch['attention_mask'],
                pixel_values=batch['pixel_values']
            )

            # Calculate loss
            loss = self.criterion(logits, labels)

            # Backward pass
            loss.backward()

            # Gradient clipping
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)

            # Optimizer step
            self.optimizer.step()

            # Statistics
            total_loss += loss.item()
            preds = torch.argmax(logits, dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

            # Update progress bar
            pbar.set_postfix({
                'loss': f'{loss.item():.4f}',
                'acc': f'{correct/total:.3f}'
            })

        avg_loss = total_loss / len(train_loader)
        accuracy = correct / total

        self.history['train_loss'].append(avg_loss)
        self.history['train_acc'].append(accuracy)

        return avg_loss, accuracy

    def evaluate(self, data_loader, mode='val'):
        """Evaluate model"""
        self.model.eval()
        total_loss = 0
        correct = 0
        total = 0

        all_preds = []
        all_labels = []
        all_probs = []

        with torch.no_grad():
            pbar = tqdm(data_loader, desc=f"{mode.capitalize()} Evaluation")
            for batch in pbar:
                batch = {k: v.to(self.device) for k, v in batch.items()}
                labels = batch['labels']

                # Forward pass
                logits = self.model(
                    input_ids=batch['input_ids'],
                    attention_mask=batch['attention_mask'],
                    pixel_values=batch['pixel_values']
                )

                # Calculate loss
                loss = self.criterion(logits, labels)
                total_loss += loss.item()

                # Get predictions and probabilities
                probs = torch.softmax(logits, dim=1)
                preds = torch.argmax(logits, dim=1)

                correct += (preds == labels).sum().item()
                total += labels.size(0)

                # Store for metrics
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(labels.cpu().numpy())
                all_probs.extend(probs.cpu().numpy())

                pbar.set_postfix({
                    'loss': f'{loss.item():.4f}',
                    'acc': f'{correct/total:.3f}'
                })

        avg_loss = total_loss / len(data_loader)
        accuracy = correct / total

        if mode == 'val':
            self.history['val_loss'].append(avg_loss)
            self.history['val_acc'].append(accuracy)
        elif mode == 'test':
            self.history['test_loss'] = avg_loss
            self.history['test_acc'] = accuracy

        return avg_loss, accuracy, all_preds, all_labels, all_probs

    def save_checkpoint(self, path, epoch, is_best=False):
        """Save model checkpoint"""
        checkpoint = {
            'epoch': epoch,
            'model_state_dict': self.model.state_dict(),
            'optimizer_state_dict': self.optimizer.state_dict(),
            'scheduler_state_dict': self.scheduler.state_dict(),
            'history': self.history
        }

        # Ensure the target directory for checkpoints exists
        os.makedirs(path, exist_ok=True) # Modified line

        if is_best:
            save_path = os.path.join(path, 'best_model.pth')
        else:
            save_path = os.path.join(path, f'checkpoint_epoch_{epoch}.pth')

        torch.save(checkpoint, save_path)
        print(f"  ✓ Saved checkpoint to {save_path}")

    def load_checkpoint(self, path):
        """Load model checkpoint"""
        checkpoint = torch.load(path, map_location=self.device)
        self.model.load_state_dict(checkpoint['model_state_dict'])
        self.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        self.scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
        self.history = checkpoint['history']
        return checkpoint['epoch']

# ==============================================================================
# 2. EVALUATION METRICS (COMPLETED)
# ==============================================================================

def calculate_metrics(true_labels, predictions, probabilities, id2label):
    """Calculate comprehensive metrics"""
    from sklearn.metrics import roc_auc_score, precision_score, recall_score
    from sklearn.preprocessing import label_binarize

    n_classes = len(id2label)

    # Convert true_labels and predictions to numpy arrays if they aren't already
    true_labels = np.asarray(true_labels)
    predictions = np.asarray(predictions)

    # Basic metrics
    accuracy = accuracy_score(true_labels, predictions)
    f1_macro = f1_score(true_labels, predictions, average='macro', zero_division=0)
    precision_macro = precision_score(true_labels, predictions, average='macro', zero_division=0)
    recall_macro = recall_score(true_labels, predictions, average='macro', zero_division=0)

    # AUC
    auc_ovr = auc_ovo = np.nan
    if n_classes > 1 and probabilities is not None:
        try:
            true_binary = label_binarize(true_labels, classes=range(n_classes))
            auc_ovr = roc_auc_score(true_binary, probabilities, average='macro', multi_class='ovr')
            auc_ovo = roc_auc_score(true_binary, probabilities, average='macro', multi_class='ovo')
        except:
            pass

    # Confusion matrix
    cm = confusion_matrix(true_labels, predictions)

    # Per-class metrics
    per_class = {}
    for class_id in range(n_classes):
        class_mask = (true_labels == class_id)
        if class_mask.any():
            class_acc = (predictions[class_mask] == class_id).mean()
            per_class[class_id] = {
                'accuracy': float(class_acc),
                'label': id2label[class_id]
            }

    return {
        'accuracy': float(accuracy),
        'f1_macro': float(f1_macro),
        'precision_macro': float(precision_macro),
        'recall_macro': float(recall_macro),
        'auc_ovr': float(auc_ovr) if not np.isnan(auc_ovr) else None,
        'auc_ovo': float(auc_ovo) if not np.isnan(auc_ovo) else None,
        'confusion_matrix': cm.tolist(),
        'per_class': per_class
    }

def plot_confusion_matrix(cm, class_names, title='Confusion Matrix', save_path=None):
    """Plot confusion matrix - COMPLETED"""
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
               xticklabels=class_names,
               yticklabels=class_names)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.title(title)
    plt.tight_layout()

    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        plt.savefig(save_path, dpi=150, bbox_inches='tight')

    plt.show()

def plot_training_history(trainer, save_path='results/training_history.png'):
    """Plot training and validation curves"""
    os.makedirs('results', exist_ok=True)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    # Loss plot
    ax1.plot(trainer.history['train_loss'], label='Train Loss', marker='o', linewidth=2)
    ax1.plot(trainer.history['val_loss'], label='Val Loss', marker='s', linewidth=2)
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss')
    ax1.set_title('Training and Validation Loss')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # Accuracy plot
    ax2.plot(trainer.history['train_acc'], label='Train Acc', marker='o', linewidth=2)
    ax2.plot(trainer.history['val_acc'], label='Val Acc', marker='s', linewidth=2)
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy')
    ax2.set_title('Training and Validation Accuracy')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim([0, 1])

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')

    plt.show()

# ==============================================================================
# MEDFUSION MODEL ARCHITECTURE (Moved from medfusion_model.py)
# ==============================================================================

class MedFusion(nn.Module):
    """
    MedFusion: Multimodal VQA model

    Truth: We're using Bio_ClinicalBERT for text and a Simple CNN for images
    NOT using BiomedCLIP (despite earlier claims in architecture diagram)
    """

    def __init__(self, num_classes=5, dropout=0.3, use_simple_cnn=True):
        super().__init__()

        print("Initializing MedFusion...")
        print("  Text encoder: Bio_ClinicalBERT")
        print("  Image encoder: Simple CNN (not BiomedCLIP)")

        # ============================================
        # TEXT ENCODER: Bio_ClinicalBERT
        # ============================================
        try:
            self.text_encoder = AutoModel.from_pretrained(
                "emilyalsentzer/Bio_ClinicalBERT"
            )
            self.text_proj = nn.Linear(768, 256)
            print("  ✓ Loaded Bio_ClinicalBERT")
        except:
            print("  ✗ Could not load Bio_ClinicalBERT, using placeholder")
            self.text_encoder = None
            self.text_proj = nn.Linear(768, 256)

        # ============================================
        # IMAGE ENCODER: Simple CNN (TRUTH)
        # ============================================
        if use_simple_cnn:
            # This is what you actually used based on 20% baseline
            self.image_encoder = nn.Sequential(
                # Block 1
                nn.Conv2d(3, 16, kernel_size=3, padding=1),
                nn.BatchNorm2d(16),
                nn.ReLU(),
                nn.MaxPool2d(2),  # 224 -> 112

                # Block 2
                nn.Conv2d(16, 32, kernel_size=3, padding=1),
                nn.BatchNorm2d(32),
                nn.ReLU(),
                nn.MaxPool2d(2),  # 112 -> 56

                # Block 3
                nn.Conv2d(32, 64, kernel_size=3, padding=1),
                nn.BatchNorm2d(64),
                nn.ReLU(),
                nn.MaxPool2d(2),  # 56 -> 28

                # Global pooling
                nn.AdaptiveAvgPool2d((1, 1)),
                nn.Flatten(),
                nn.Linear(64, 256)
            )
            print("  ✓ Using Simple CNN image encoder")
        else:
            # Placeholder for actual BiomedCLIP (not implemented)
            self.image_encoder = None
            print("  ✗ BiomedCLIP not implemented")

        # ============================================
        # FUSION AND CLASSIFICATION
        # ============================================
        self.fusion_dropout = nn.Dropout(dropout)
        self.fusion_layer = nn.Linear(512, 256)  # 256 + 256 = 512
        self.classifier = nn.Linear(256, num_classes)

        # Tokenizer
        try:
            self.tokenizer = AutoTokenizer.from_pretrained(
                "emilyalsentzer/Bio_ClinicalBERT"
            )
        except:
            self.tokenizer = None

        # Freeze text encoder initially
        if self.text_encoder:
            for param in self.text_encoder.parameters():
                param.requires_grad = False

        print(f"  Total parameters: {sum(p.numel() for p in self.parameters()):,}")
        print(f"  Trainable parameters: {sum(p.numel() for p in self.parameters() if p.requires_grad):,}")

    def forward(self, input_ids, attention_mask, pixel_values):
        """
        Forward pass

        Args:
            input_ids: Tokenized text [batch, seq_len]
            attention_mask: Attention mask [batch, seq_len]
            pixel_values: Images [batch, 3, 224, 224]
        """
        batch_size = pixel_values.shape[0]

        # ============================================
        # TEXT ENCODING
        # ============================================
        if self.text_encoder is not None:
            text_outputs = self.text_encoder(
                input_ids=input_ids,
                attention_mask=attention_mask
            )
            # Use [CLS] token
            text_features = text_outputs.last_hidden_state[:, 0, :]
        else:
            # Placeholder if text encoder failed to load
            text_features = torch.randn(batch_size, 768, device=pixel_values.device)

        text_features = F.relu(self.text_proj(text_features))

        # ============================================
        # IMAGE ENCODING
        # ============================================
        if self.image_encoder is not None:
            image_features = self.image_encoder(pixel_values)
        else:
            # Placeholder
            image_features = torch.randn(batch_size, 256, device=pixel_values.device)

        # ============================================
        # LATE FUSION
        # ============================================
        fused_features = torch.cat([text_features, image_features], dim=1)
        fused_features = self.fusion_dropout(fused_features)

        # ============================================
        # CLASSIFICATION
        # ============================================
        fused_features = F.relu(self.fusion_layer(fused_features))
        logits = self.classifier(fused_features)

        return logits

    def get_tokenizer(self):
        """Get tokenizer for text preprocessing"""
        return self.tokenizer

# ==============================================================================
# DATASET CLASS (Moved from medfusion_model.py)
# ==============================================================================

class MedFusionDataset(torch.utils.data.Dataset):
    """Dataset for MedFusion with image downloading"""

    def __init__(self, dataset_split, tokenizer, max_length=128, image_size=224):
        self.dataset = dataset_split
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.image_size = image_size

        # Image transforms
        self.transform = transforms.Compose([
            transforms.Resize((image_size, image_size)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                               std=[0.229, 0.224, 0.225])
        ])

        # Preprocess texts
        self._preprocess_texts()

    def _preprocess_texts(self):
        """Preprocess all text once"""
        self.texts = []

        for example in self.dataset:
            question = example["Question"]

            # Get options
            options = []
            for letter in ["A", "B", "C", "D", "E"]:
                col_name = f"Answer{letter}"
                if col_name in example and example[col_name]:
                    options.append(f"{letter}. {example[col_name]}")

            # Format: "Question: [text] Options: A. ... B. ..."
            if options:
                text = f"Question: {question} Options: " + " | ".join(options[:3])
            else:
                text = f"Question: {question}"

            self.texts.append(text)

    def __len__(self):
        return len(self.dataset)

    def _download_image(self, url):
        """Download image from URL"""
        try:
            response = requests.get(url, timeout=5)
            image = Image.open(BytesIO(response.content)).convert("RGB")
            return image
        except:
            # Return black image if download fails
            return Image.new('RGB', (self.image_size, self.image_size), (0, 0, 0))

    def __getitem__(self, idx):
        example = self.dataset[idx]

        # Text
        text = self.texts[idx]
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt"
        )

        # Image
        image_url = example["Image url"]
        image = self._download_image(image_url)
        image_tensor = self.transform(image)

        # Label
        label = torch.tensor(example["label"], dtype=torch.long)

        return {
            "input_ids": encoding["input_ids"].squeeze(),
            "attention_mask": encoding["attention_mask"].squeeze(),
            "pixel_values": image_tensor,
            "labels": label
        }

# ==============================================================================
# 3. MAIN TRAINING PIPELINE (NEW - TO CONNECT EVERYTHING)
# ==============================================================================

def run_training_pipeline(splits_path='data/splits', output_dir='checkpoints', epochs=10):
    """
    Complete training pipeline that connects all components
    """
    print("="*60)
    print("MEDFUSION TRAINING PIPELINE")
    print("="*60)

    try:
        # 1. Load data splits
        from datasets import DatasetDict
        splits = DatasetDict.load_from_disk(splits_path)
        print(f"✓ Loaded data splits: {len(splits['train'])} train, "
              f"{len(splits['val'])} val, {len(splits['test'])} test")

        # 2. Load label mappings
        with open('data/label_mappings.json', 'r') as f:
            label_mappings = json.load(f)
            id2label = {int(k): v for k, v in label_mappings['id2label'].items()}

        # 3. Create dataset (removed problematic import, classes are now defined directly)
        tokenizer = AutoTokenizer.from_pretrained("emilyalsentzer/Bio_ClinicalBERT")

        train_dataset = MedFusionDataset(splits['train'], tokenizer)
        val_dataset = MedFusionDataset(splits['val'], tokenizer)
        test_dataset = MedFusionDataset(splits['test'], tokenizer)

        print("✓ Created datasets")

        # 4. Create dataloaders
        train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True, num_workers=0)
        val_loader = DataLoader(val_dataset, batch_size=4, shuffle=False, num_workers=0)
        test_loader = DataLoader(test_dataset, batch_size=4, shuffle=False, num_workers=0)

        # 5. Initialize model
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model = MedFusion(num_classes=len(id2label))

        # 6. Calculate class weights
        trainer = MedFusionTrainer(model, device)
        train_labels = splits['train']['label']
        class_weights = trainer.calculate_class_weights(train_labels)

        # Reinitialize trainer with class weights
        trainer = MedFusionTrainer(model, device, class_weights=class_weights)

        print(f"✓ Initialized model on {device}")
        print(f"✓ Using class weights: {class_weights}")

        # 7. Training loop
        best_val_acc = 0

        for epoch in range(1, epochs + 1):
            print(f"\nEpoch {epoch}/{epochs}")

            # Train
            train_loss, train_acc = trainer.train_epoch(train_loader, epoch)

            # Validate
            val_loss, val_acc, _, _, _ = trainer.evaluate(val_loader, 'val')

            print(f"  Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.3f}")
            print(f"  Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.3f}")

            # Save best model
            if val_acc > best_val_acc:
                best_val_acc = val_acc
                trainer.save_checkpoint(output_dir, epoch, is_best=True)
                print(f"  ✓ New best model (Val Acc: {val_acc:.3f})")

            # Save checkpoint every 2 epochs
            if epoch % 2 == 0:
                trainer.save_checkpoint(output_dir, epoch)

        # 8. Final test evaluation
        print("\n" + "-"*60)
        print("FINAL TEST EVALUATION")
        print("-"*60)

        test_loss, test_acc, test_preds_list, test_labels_list, test_probs = trainer.evaluate(test_loader, 'test')

        # Convert lists to NumPy arrays for metric calculation
        test_labels_np = np.array(test_labels_list)
        test_preds_np = np.array(test_preds_list)

        # Calculate metrics
        metrics = calculate_metrics(test_labels_np, test_preds_np, test_probs, id2label)

        print(f"\nTest Results:")
        print(f"  Accuracy: {test_acc:.3f}")
        print(f"  F1-Macro: {metrics['f1_macro']:.3f}")
        print(f"  Precision: {metrics['precision_macro']:.3f}")
        print(f"  Recall: {metrics['recall_macro']:.3f}")

        # 9. Plot confusion matrix
        class_names = [id2label[i] for i in range(len(id2label))]
        cm = confusion_matrix(test_labels_np, test_preds_np)
        plot_confusion_matrix(cm, class_names,
                             title='MedFusion Confusion Matrix (Test Set)',
                             save_path='results/medfusion_confusion.png')

        # 10. Plot training history
        plot_training_history(trainer, save_path='results/training_history.png')

        # 11. Save results
        results = {
            'medfusion': {
                'accuracy': float(test_acc),
                'f1_macro': float(metrics['f1_macro']),
                'precision_macro': float(metrics['precision_macro']),
                'recall_macro': float(metrics['recall_macro']),
                'auc_ovr': metrics['auc_ovr'],
                'auc_ovo': metrics['auc_ovo'],
                'predictions': test_preds_np.tolist(),
                'true_labels': test_labels_np.tolist()
            }
        }

        os.makedirs('results', exist_ok=True)
        with open('results/medfusion_results.json', 'w') as f:
            json.dump(results, f, indent=2)

        print(f"\n✓ Results saved to 'results/medfusion_results.json'")
    except Exception as e:
        print(f"An error occurred during training pipeline: {e}")

# ==============================================================================
# 4. MAIN EXECUTION
# ==============================================================================

if __name__ == "__main__":
    print("Running MedFusion training pipeline...")
    run_training_pipeline()